#!/bin/bash

if [ -z ${CURRDIR} ];
then
    "Variable CURRDIR is not set.  Please check!"
    exit
fi

export BINDIR=${CURRDIR}/target/classes/

#generated during build (see pom.xml)
DEPS=$(<"${CURRDIR}/classpath")
CLASSPATH="${BINDIR}:${DEPS}"

OS_KERNEL=`uname -s`
if [ $OS_KERNEL = "Darwin" ]
    then
        DOTPATH="/usr/local/bin/dot"
    else
        DOTPATH="/usr/bin/dot"
fi

export CLASSPATH
export OS_KERNEL
